version: "3.7"

services:
  nginx:
    build: nginx
    restart: always
    depends_on:
      - api
    ports:
      - 8080:80
      - 8081:443

  api:
    build: api
    restart: always
    depends_on:
      - database
    ports:
      - 9000:9000
    volumes:
      - ./api:/var/www/:Z

  database:
    image: postgres:9.6.13-alpine
    environment:
      POSTGRES_DB: test_server
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123
    volumes:
      - ./database:/var/lib/postgresql:Z
    ports:
      - 5432:5432
